opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - syntactic_sugar # Find all the available rules by running: `swiftlint rules`
  - closure_end_indentation
  - closure_body_length
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - force_unwrapping
  - indentation_width
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments



excluded:
  - Carthage
  - Pods

colon:
  apply_to_dictionaries: false

# indentation: 2

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error