# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'detach2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for detach2
pod "Introspect"


  target 'detach2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'detach2UITests' do
    # Pods for testing
  end

end
