# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'detach2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for detach2
  pod "Introspect"
  pod 'Willow', '~> 5.0'
  pod 'Moya', '~> 14.0'



  target 'detach2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'detach2UITests' do
    # Pods for testing
  end

end


target 'DetachExtension' do 
  use_frameworks!

  pod 'Willow', '~> 5.0'

end
